language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install qt58base
    - source /opt/qt58/bin/qt58-env.sh

script:
  - qmake PREFIX=/usr
  - make -j4
  - make INSTALL_ROOT=appdir install ; find .
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/untagged-f85f3d9f6ab286aaf4bd/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/edfbrowser.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/edfbrowser.desktop -appimage 
  - curl --upload-file ./EDFbrowser-*.AppImage https://transfer.sh/EDFbrowser-git$(git rev-parse --short HEAD)-x86_64.AppImage 
